local a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y 
TEAM_UNKNOWN = 0
TEAM_ORDER = 100
TEAM_CHAOS = 200
TEAM_NEUTRAL = 300
TEAM_MAX = 400
HOSTILE = 1
INACTIVE = 0
a = {}
a[1] = "TwistedLizardElder"  --x2 
a[2] = "LizardElder"  --x2 
a[3] = "AncientGolem"  --x2
a[4] = "Golem"
a[5] = "GiantWolf" --x2
a[6] = "Wraith"
a[7] = "Dragon"
a[8] = "blueDragon"
a[9] = "RabidWolf"  -- en bas 
a[10] = "Ghast" -- en haut 
a[11] = "OdinShieldRelic"
NeutralMinionNames = a
HERO_EXP_RADIUS = 800
a = {}
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.TwistedLizardElder = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.LizardElder = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.Golem = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.AncientGolem = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.GiantWolf = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.Wraith = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.Dragon = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.blueDragon = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.RabidWolf = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 200
b.SoulGiven = 0
a.Ghast = b
b = {}
b.GoldGiven = 0
b.ExpGiven = 0
b.SoulGiven = 0
a.OdinShieldRelic = b
b = {}
DefaultNeutralMinionValues = a
NeutralTimers = {}
a = {}
b = {}
e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(3129.91846, 55.0609, 6775.85403) --bluebuff order
b[1] = e
b[2] = f
b[3] = g
b[4] = h
b[5] = i
b[6] = j
b[7] = k
b[8] = l
b[9] = m
b[10] = n
b[11] = o
b[12] = p
b[13] = q
b[14] = r
b[15] = s
b[16] = t
b[17] = u
b[18] = v
b[19] = w
b[20] = x
b[21] = y
c = {}
f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(10922.62846, 50, 9816.98403)--bluebuff chaos
c[1] = f
c[2] = g
c[3] = h
c[4] = i
c[5] = j
c[6] = k
c[7] = l
c[8] = m
c[9] = n
c[10] = o
c[11] = p
c[12] = q
c[13] = r
c[14] = s
c[15] = t
c[16] = u
c[17] = v
c[18] = w
c[19] = x
c[20] = y
d = {}
g ,h, i, j, k, l, m, n, o, p, q, r, s, t, u, v , w , x , y  = Make3DPoint(11379.71846, 51.141, 7413.35403) --wraith order
d[1] = g
d[2] = h
d[3] = i
d[4] = j
d[5] = k
d[6] = l
d[7] = m
d[8] = n
d[9] = o
d[10] = p
d[11] = q
d[12] = r
d[13] = s
d[14] = t
d[15] = u
d[16] = v
d[17] = w
d[18] = x
d[19] = y
e = {}
h, i, j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(3202.50846, 56.8674, 9581.83403) --wraith chaos
e[1] = h
e[2] = i
e[3] = j
e[4] = k
e[5] = l
e[6] = m
e[7] = n
e[8] = o
e[9] = p
e[10] = q
e[11] = r
e[12] = s
e[13] = t
e[14] = u
e[15] = v
e[16] = w
e[17] = x
e[18] = y
f = {}
i, j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(9953.470745, 50.652954, 6121.947409) --redbuff order
f[1] = i
f[2] = j
f[3] = k
f[4] = l
f[5] = m
f[6] = n
f[7] = o
f[8] = p
f[9] = q
f[10] = r
f[11] = s
f[12] = t
f[13] = u
f[14] = v
f[15] = w
f[16] = x
f[17] = y
g = {}
j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(4925.14846, 50.7511, 10534.01403) --redbuff chaos
g[1] = j
g[2] = k
g[3] = l
g[4] = m
g[5] = n
g[6] = o
g[7] = p
g[8] = q
g[9] = r
g[10] = s
g[11] = t
g[12] = u
g[13] = v
g[14] = w
g[15] = x
g[16] = y
h = {}
k, l, m, n, o, p, q, r, s, t, u, v , w , x , y  = Make3DPoint(4561.62846, 54.8491, 5883.68403) --golem order
h[1] = k
h[2] = l
h[3] = m
h[4] = n
h[5] = o
h[6] = p
h[7] = q
h[8] = r
h[9] = s
h[10] = t
h[11] = u
h[12] = v
h[13] = w
h[14] = x
h[15] = y
i = {}
l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(9388.151898, 51.239746, 11033.408346) --golem chaos
i[1] = l
i[2] = m
i[3] = n
i[4] = o
i[5] = p
i[6] = q
i[7] = r
i[8] = s
i[9] = t
i[10] = u
i[11] = v
i[12] = w
i[13] = x
i[14] = y
j = {}
m , n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(5672.38846, 52.2263, 7592.47403) --redbufftt order
j[1] = m
j[2] = n
j[3] = o
j[4] = p
j[5] = q
j[6] = r
j[7] = s
j[8] = t
j[9] = u
j[10] = v
j[11] = w
j[12] = x
j[13] = y
k = {}
n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(8710.08846, 54.6353, 9570.68403) --redbufftt order
k[1] = n
k[2] = o
k[3] = p
k[4] = q
k[5] = r
k[6] = s
k[7] = t
k[8] = u
k[9] = v
k[10] = w
k[11] = x
k[12] = y
l = {}
o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(7077.092327, 47.607788, 4930.457663) --dragon top bluedragon 
l[1] = o
l[2] = p
l[3] = q
l[4] = r
l[5] = s
l[6] = t
l[7] = u
l[8] = v
l[9] = w
l[10] = x
l[11] = y
m = {}
p, q, r, s, t, u , v , w , x , y = Make3DPoint(7304.123577, 24.390137, 11250.445944) --dragon bot srdragon 
m[1] = p
m[2] = q
m[3] = r
m[4] = s
m[5] = t
m[6] = u
m[7] = v
m[8] = w
m[9] = x
m[10] = y
n = {}
q, r, s, t, u , v , w , x , y = Make3DPoint(7047.62846, 54, 1534.98403) --rabidwolf crab bot 
n[1] = q
n[2] = r
n[3] = s
n[4] = t
n[5] = u
n[6] = v
n[7] = w
n[8] = x
n[9] = y
o = {}
 r, s, t, u , v , w , x , y = Make3DPoint(7302.62846, 54, 13725.98403) --ghast crab top 
o[1] = r
o[2] = s
o[3] = t
o[4] = u
o[5] = v
o[6] = w
o[7] = x
o[8] = y
p = {}
 s, t, u , v , w , x , y = Make3DPoint(4533, 50, 4668) --odinshield bot order
p[1] = s
p[2] = t
p[3] = u
p[4] = v
p[5] = w
p[6] = x
p[7] = y
q = {}
 t, u , v , w , x , y = Make3DPoint(5100, 50, 11582) --odinshield top order
q[1] = t
q[2] = u
q[3] = v
q[4] = w
p[5] = x
p[6] = y
r = {}
 u , v , w , x , y = Make3DPoint(9783, 50, 4781)  --odinshield bot chaos
r[1] = u
r[2] = v
r[3] = w
r[4] = x
r[5] = y
s = {}
v , w , x , y = Make3DPoint(9205, 50, 11582) --odinshield top chaos
s[1] = v
s[2] = w
s[3] = x
s[4] = y

---
a[1] = b
a[2] = c
a[3] = d
a[4] = e
a[5] = f
a[6] = g
a[7] = h
a[8] = i
a[9] = j
a[10] = k
a[11] = l
a[12] = m
a[13] = n
a[14] = o
a[15] = p
a[16] = q
a[17] = r
a[18] = s
CampSpawnPoints = a
a = {}
b = {}
e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(3129.91846, 55.0609, 6675.85403) --bluebuff order
b[1] = e
b[2] = f
b[3] = g
b[4] = h
b[5] = i
b[6] = j
b[7] = k
b[8] = l
b[9] = m
b[10] = n
b[11] = o
b[12] = p
b[13] = q
b[14] = r
b[15] = s
b[16] = t
b[17] = u
b[18] = v
b[19] = w
b[20] = x
b[21] = y
c = {}
f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(10922.62846, 50, 9716.98403)--bluebuff chaos
c[1] = f
c[2] = g
c[3] = h
c[4] = i
c[5] = j
c[6] = k
c[7] = l
c[8] = m
c[9] = n
c[10] = o
c[11] = p
c[12] = q
c[13] = r
c[14] = s
c[15] = t
c[16] = u
c[17] = v
c[18] = w
c[19] = x
c[20] = y
d = {}
g ,h, i, j, k, l, m, n, o, p, q, r, s, t, u, v , w , x , y  = Make3DPoint(11379.71846, 51.141, 7313.35403) --wraith order
d[1] = g
d[2] = h
d[3] = i
d[4] = j
d[5] = k
d[6] = l
d[7] = m
d[8] = n
d[9] = o
d[10] = p
d[11] = q
d[12] = r
d[13] = s
d[14] = t
d[15] = u
d[16] = v
d[17] = w
d[18] = x
d[19] = y
e = {}
h, i, j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(3202.50846, 56.8674, 9481.83403) --wraith chaos
e[1] = h
e[2] = i
e[3] = j
e[4] = k
e[5] = l
e[6] = m
e[7] = n
e[8] = o
e[9] = p
e[10] = q
e[11] = r
e[12] = s
e[13] = t
e[14] = u
e[15] = v
e[16] = w
e[17] = x
e[18] = y
f = {}
i, j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(9953.470745, 50.652954, 6021.947409) --redbuff order
f[1] = i
f[2] = j
f[3] = k
f[4] = l
f[5] = m
f[6] = n
f[7] = o
f[8] = p
f[9] = q
f[10] = r
f[11] = s
f[12] = t
f[13] = u
f[14] = v
f[15] = w
f[16] = x
f[17] = y
g = {}
j, k, l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(4925.14846, 50.7511, 10434.01403) --redbuff chaos
g[1] = j
g[2] = k
g[3] = l
g[4] = m
g[5] = n
g[6] = o
g[7] = p
g[8] = q
g[9] = r
g[10] = s
g[11] = t
g[12] = u
g[13] = v
g[14] = w
g[15] = x
g[16] = y
h = {}
k, l, m, n, o, p, q, r, s, t, u, v , w , x , y  = Make3DPoint(4561.62846, 54.8491, 5783.68403) --golem order
h[1] = k
h[2] = l
h[3] = m
h[4] = n
h[5] = o
h[6] = p
h[7] = q
h[8] = r
h[9] = s
h[10] = t
h[11] = u
h[12] = v
h[13] = w
h[14] = x
h[15] = y
i = {}
l, m, n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(9388.151898, 51.239746, 10933.408346) --golem chaos
i[1] = l
i[2] = m
i[3] = n
i[4] = o
i[5] = p
i[6] = q
i[7] = r
i[8] = s
i[9] = t
i[10] = u
i[11] = v
i[12] = w
i[13] = x
i[14] = y
j = {}
m , n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(5672.38846, 52.2263, 7492.47403) --redbufftt order
j[1] = m
j[2] = n
j[3] = o
j[4] = p
j[5] = q
j[6] = r
j[7] = s
j[8] = t
j[9] = u
j[10] = v
j[11] = w
j[12] = x
j[13] = y
k = {}
n, o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(8710.08846, 54.6353, 9470.68403) --redbufftt order
k[1] = n
k[2] = o
k[3] = p
k[4] = q
k[5] = r
k[6] = s
k[7] = t
k[8] = u
k[9] = v
k[10] = w
k[11] = x
k[12] = y
l = {}
o, p, q, r, s, t, u , v , w , x , y = Make3DPoint(7077.092327, 47.607788, 4830.457663) --dragon top bluedragon 
l[1] = o
l[2] = p
l[3] = q
l[4] = r
l[5] = s
l[6] = t
l[7] = u
l[8] = v
l[9] = w
l[10] = x
l[11] = y
m = {}
p, q, r, s, t, u , v , w , x , y = Make3DPoint(7304.123577, 24.390137, 11150.445944) --dragon bot srdragon 
m[1] = p
m[2] = q
m[3] = r
m[4] = s
m[5] = t
m[6] = u
m[7] = v
m[8] = w
m[9] = x
m[10] = y
n = {}
q, r, s, t, u , v , w , x , y = Make3DPoint(7047.62846, 54, 1434.98403) --rabidwolf crab bot 
n[1] = q
n[2] = r
n[3] = s
n[4] = t
n[5] = u
n[6] = v
n[7] = w
n[8] = x
n[9] = y
o = {}
 r, s, t, u , v , w , x , y = Make3DPoint(7302.62846, 54, 13625.98403) --ghast crab top 
o[1] = r
o[2] = s
o[3] = t
o[4] = u
o[5] = v
o[6] = w
o[7] = x
o[8] = y
p = {}
 s, t, u , v , w , x , y = Make3DPoint(4533, 50, 4568) --odinshield bot order
p[1] = s
p[2] = t
p[3] = u
p[4] = v
p[5] = w
p[6] = x
p[7] = y
q = {}
 t, u , v , w , x , y = Make3DPoint(5100, 50, 11482) --odinshield top order
q[1] = t
q[2] = u
q[3] = v
q[4] = w
p[5] = x
p[6] = y
r = {}
 u , v , w , x , y = Make3DPoint(9783, 50, 4681)  --odinshield bot chaos
r[1] = u
r[2] = v
r[3] = w
r[4] = x
r[5] = y
s = {}
v , w , x , y = Make3DPoint(9205, 50, 11482) --odinshield top chaos
s[1] = v
s[2] = w
s[3] = x
s[4] = y

---
a[1] = b
a[2] = c
a[3] = d
a[4] = e
a[5] = f
a[6] = g
a[7] = h
a[8] = i
a[9] = j
a[10] = k
a[11] = l
a[12] = m
a[13] = n
a[14] = o
a[15] = p
a[16] = q
a[17] = r
a[18] = s
CampFacePoints = a
CAMPTYPE_DRAGON = 1
CAMPTYPE_SMALLGOLEMS = 2
CAMPTYPE_SMALLGOLEMS2 = 3
CAMPTYPE_WRAITHS = 4
CAMPTYPE_WRAITHS2 = 5
CAMPTYPE_REDBUFF = 6
CAMPTYPE_REDBUFF2 = 7
CAMPTYPE_BLUEBUFF = 8
CAMPTYPE_BLUEBUFF2 = 9
CAMPTYPE_OWLBEAR = 10
CAMPTYPE_OWLBEAR2 = 11
CAMPTYPE_NASHOR = 12
CAMPTYPE_CRAB = 13
CAMPTYPE_CRAB2 = 14
CAMPTYPE_RELIC = 15
CAMPTYPE_RELIC2 = 16
CAMPTYPE_RELIC3 = 17
CAMPTYPE_RELIC4 = 18
a = {}
c = {}
c[1] = "blueDragon"
a[CAMPTYPE_DRAGON] = c
c = {}
c[1] = "Golem"    
a[CAMPTYPE_SMALLGOLEMS] = c
c = {}
c[1] = "Golem"  
a[CAMPTYPE_SMALLGOLEMS2] = c
c = {}
c[1] = "Wraith"  
a[CAMPTYPE_WRAITHS] = c
c = {}
c[1] = "Wraith"
a[CAMPTYPE_WRAITHS2] = c
c = {}
c[1] = "LizardElder"
a[CAMPTYPE_REDBUFF] = c --x2
c = {}
c[1] = "LizardElder"
a[CAMPTYPE_REDBUFF2] = c --x2
c = {}
c[1] = "AncientGolem"  --x2
a[CAMPTYPE_BLUEBUFF] = c
c = {}
c[1] = "AncientGolem"  --x2
a[CAMPTYPE_BLUEBUFF2] = c
c = {}
c[1] = "TwistedLizardElder"
a[CAMPTYPE_OWLBEAR] = c
c = {}
c[1] = "TwistedLizardElder"
a[CAMPTYPE_OWLBEAR2] = c
c = {}
c[1] = "RabidWolf"
a[CAMPTYPE_CRAB] = c
c = {}
c[1] = "Ghast"
a[CAMPTYPE_CRAB2] = c
c = {}
c[1] = "Dragon"
a[CAMPTYPE_NASHOR] = c
c = {}
c[1] = "OdinShieldRelic"
a[CAMPTYPE_RELIC] = c
c = {}
c[1] = "OdinShieldRelic" --
a[CAMPTYPE_RELIC2] = c
c = {}
c[1] = "OdinShieldRelic" --
a[CAMPTYPE_RELIC3] = c
c = {}
c[1] = "OdinShieldRelic" --
a[CAMPTYPE_RELIC4] = c
PredefinedCamps = a
a = {}
c = {}
c[1] = "EVENT_ON_KILL_DRAGON"
a[CAMPTYPE_DRAGON] = c
c = {}
c[1] = "EVENT_ON_KILL_WORM"
a[CAMPTYPE_NASHOR] = c
PredefinedCampKillEvents = a
a = {}
c = {}
c[1] = "EVENT_ON_KILL_DRAGON_SPECTATOR"
a[CAMPTYPE_DRAGON] = c
c = {}
c[1] = "EVENT_ON_KILL_WORM_SPECTATOR"
a[CAMPTYPE_NASHOR] = c
PredefinedCampKillEventsForSpectator = a
a = {}
a[1] = {}
a[2] = {}
a[3] = {}
a[4] = {}
a[5] = {}
a[6] = {}
a[7] = {}
a[8] = {}
a[9] = {}
a[10] = {}
a[11] = {}
a[12] = {}
a[13] = {}
a[14] = {}
a[15] = {}
a[16] = {}
a[17] = {}
a[18] = {}
NeutralMinionCamps = a
NUMBER_OF_CAMPS = #NeutralMinionCamps
NeutralMinionInit = function()
    local v, w, x, y, z, A, B
    v, w, x = pairs(NeutralMinionNames)
    for y, z in v, w, x do
        PreloadCharacter(z)
    end
    for y = 1, NUMBER_OF_CAMPS, 1 do
        NeutralMinionCamps[y].Positions = CampSpawnPoints[y]
        NeutralMinionCamps[y].FacePositions = CampFacePoints[y]
        NeutralMinionCamps[y].UniqueNames = {}
        NeutralMinionCamps[y].AliveTracker = {}
        NeutralMinionCamps[y].Team = TEAM_NEUTRAL
        NeutralMinionCamps[y].DamageBonus = 0
        NeutralMinionCamps[y].HealthBonus = 0
        NeutralMinionCamps[y].AIState = INACTIVE
        NeutralMinionCamps[y].GroupsRespawnTime = 100
        NeutralMinionCamps[y].CampLevel = 1
        NeutralMinionCamps[y].TimerType = ""
        NeutralMinionCamps[y].SpawnDuration = 0
        NeutralMinionCamps[y].MinimapIcon = "LesserCamp"
    end
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_BLUEBUFF]
    NeutralMinionCamps[1].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[1].GroupsChance = w
    NeutralMinionCamps[1].GroupsRespawnTime = 300
    NeutralMinionCamps[1].GroupDelaySpawnTime = 15
    NeutralMinionCamps[1].GroupBuffSide = TEAM_ORDER
    NeutralMinionCamps[1].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_BLUEBUFF2]
    NeutralMinionCamps[2].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[2].GroupsChance = w
    NeutralMinionCamps[2].GroupsRespawnTime = 300
    NeutralMinionCamps[2].GroupDelaySpawnTime = 15
    NeutralMinionCamps[2].GroupBuffSide = TEAM_CHAOS
    NeutralMinionCamps[2].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_WRAITHS]
    NeutralMinionCamps[3].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[3].GroupsChance = w
    NeutralMinionCamps[3].GroupsRespawnTime = 75
    NeutralMinionCamps[3].GroupDelaySpawnTime = 0
    NeutralMinionCamps[3].GroupBuffSide = TEAM_ORDER
    NeutralMinionCamps[3].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_WRAITHS2]
    NeutralMinionCamps[4].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[4].GroupsChance = w
    NeutralMinionCamps[4].GroupsRespawnTime = 75
    NeutralMinionCamps[4].GroupDelaySpawnTime = 0
    NeutralMinionCamps[4].GroupBuffSide = TEAM_CHAOS
    NeutralMinionCamps[4].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_REDBUFF]
    NeutralMinionCamps[5].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[5].GroupsChance = w
    NeutralMinionCamps[5].GroupsRespawnTime = 300
    NeutralMinionCamps[5].GroupDelaySpawnTime = 15
    NeutralMinionCamps[5].GroupBuffSide = TEAM_ORDER
    NeutralMinionCamps[5].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_REDBUFF2]
    NeutralMinionCamps[6].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[6].GroupsChance = w
    NeutralMinionCamps[6].GroupsRespawnTime = 300
    NeutralMinionCamps[6].GroupDelaySpawnTime = 15
    NeutralMinionCamps[6].GroupBuffSide = TEAM_CHAOS
    NeutralMinionCamps[6].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_SMALLGOLEMS]
    NeutralMinionCamps[7].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[7].GroupsChance = w
    NeutralMinionCamps[7].GroupsRespawnTime = 75
    NeutralMinionCamps[7].GroupDelaySpawnTime = 0
    NeutralMinionCamps[7].GroupBuffSide = TEAM_ORDER
    NeutralMinionCamps[7].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_SMALLGOLEMS2]
    NeutralMinionCamps[8].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[8].GroupsChance = w
    NeutralMinionCamps[8].GroupsRespawnTime = 75
    NeutralMinionCamps[8].GroupDelaySpawnTime = 0
    NeutralMinionCamps[8].GroupBuffSide = TEAM_CHAOS
    NeutralMinionCamps[8].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_OWLBEAR] --redbufftt
    NeutralMinionCamps[9].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[9].GroupsChance = w
    NeutralMinionCamps[9].GroupsRespawnTime = 300
    NeutralMinionCamps[9].GroupDelaySpawnTime = 15
    NeutralMinionCamps[9].GroupBuffSide = TEAM_ORDER
    NeutralMinionCamps[9].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_OWLBEAR2] --redbufftt
    NeutralMinionCamps[10].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[10].GroupsChance = w
    NeutralMinionCamps[10].GroupsRespawnTime = 300
    NeutralMinionCamps[10].GroupDelaySpawnTime = 15
    NeutralMinionCamps[10].GroupBuffSide = TEAM_CHAOS
    NeutralMinionCamps[10].MinimapIcon = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_DRAGON]
    NeutralMinionCamps[11].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[11].GroupsChance = w
    NeutralMinionCamps[11].GroupsRespawnTime = 400
    NeutralMinionCamps[11].GroupDelaySpawnTime = 300
    NeutralMinionCamps[11].CampLevel = 3
 --   NeutralMinionCamps[6].RevealEvent = "VO_INTERACTIVE_REVEAL_ENEMY_DRAGON_KILL"
 --   NeutralMinionCamps[6].KillEvents = PredefinedCampKillEvents[CAMPTYPE_DRAGON]
 --   NeutralMinionCamps[6].SpectatorKillEvents = PredefinedCampKillEventsForSpectator[CAMPTYPE_DRAGON]
    NeutralMinionCamps[11].MinimapIcon = "Epic"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_NASHOR]
    NeutralMinionCamps[12].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[12].GroupsChance = w
    NeutralMinionCamps[12].GroupsRespawnTime = 400
    NeutralMinionCamps[12].GroupDelaySpawnTime = 300
    NeutralMinionCamps[12].CampLevel = 3
  --  NeutralMinionCamps[12].RevealEvent = "VO_INTERACTIVE_REVEAL_ENEMY_NASHOR_KILL"
  --  NeutralMinionCamps[12].KillEvents = PredefinedCampKillEvents[CAMPTYPE_NASHOR]
  --  NeutralMinionCamps[12].SpectatorKillEvents = PredefinedCampKillEventsForSpectator[CAMPTYPE_NASHOR]
    NeutralMinionCamps[12].MinimapIcon = "Epic"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_CRAB]
    NeutralMinionCamps[13].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[13].GroupsChance = w
    NeutralMinionCamps[13].GroupsRespawnTime = 250
    NeutralMinionCamps[13].GroupDelaySpawnTime = 50
    NeutralMinionCamps[13].MinimapIcon = "Camp"
    NeutralMinionCamps[13].AIScript = "" -- RiverCrab.lua this need work 
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_CRAB2]
    NeutralMinionCamps[14].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[14].GroupsChance = w
    NeutralMinionCamps[14].GroupsRespawnTime = 250
    NeutralMinionCamps[14].GroupDelaySpawnTime = 50
    NeutralMinionCamps[14].MinimapIcon = "Camp"
    NeutralMinionCamps[14].AIScript = "" --this need work
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_RELIC]
    NeutralMinionCamps[15].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[15].GroupsChance = w
    NeutralMinionCamps[15].GroupsRespawnTime = 30
    NeutralMinionCamps[15].GroupDelaySpawnTime = 30
    NeutralMinionCamps[15].GroupBuffSide = TEAM_ORDER
  --  NeutralMinionCamps[15].MinimapIcon = ""
    NeutralMinionCamps[15].AIScript = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_RELIC2]
    NeutralMinionCamps[16].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[16].GroupsChance = w
    NeutralMinionCamps[16].GroupsRespawnTime = 30
    NeutralMinionCamps[16].GroupDelaySpawnTime = 30
    NeutralMinionCamps[16].GroupBuffSide = TEAM_ORDER
 --   NeutralMinionCamps[16].MinimapIcon = ""
    NeutralMinionCamps[16].AIScript = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_RELIC3]
    NeutralMinionCamps[17].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[17].GroupsChance = w
    NeutralMinionCamps[17].GroupsRespawnTime = 30
    NeutralMinionCamps[17].GroupDelaySpawnTime = 30
    NeutralMinionCamps[17].GroupBuffSide = TEAM_CHAOS
  --  NeutralMinionCamps[17].MinimapIcon = ""
    NeutralMinionCamps[17].AIScript = "Camp"
    w = {}
    w[1] = PredefinedCamps[CAMPTYPE_RELIC4]
    NeutralMinionCamps[18].Groups = w
    w = {}
    w[1] = 100
    NeutralMinionCamps[18].GroupsChance = w
    NeutralMinionCamps[18].GroupsRespawnTime = 30
    NeutralMinionCamps[18].GroupDelaySpawnTime = 30
    NeutralMinionCamps[18].GroupBuffSide = TEAM_CHAOS
  --  NeutralMinionCamps[18].MinimapIcon = ""
    NeutralMinionCamps[18].AIScript = "Camp"
  
end
CreateRespawnNeutralTimer = function(C)
    local w
    return function()
        local D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S
        E = 0
        F = false
        NeutralMinionCamps[C].DamageBonus = NeutralMinionCamps[C].DamageBonus + 0
        NeutralMinionCamps[C].HealthBonus = NeutralMinionCamps[C].HealthBonus + 0

            for J = 1, #NeutralMinionCamps[C].Groups, 1 do
                if math.random(100) <= NeutralMinionCamps[C].GroupsChance[J] + E and F == false then
                    NeutralMinionCamps[C].AliveTracker = {}
                    print("good:  CreateRespawnNeutralTimer 1 ")
                    
                    for N = 1, #NeutralMinionCamps[C].Groups[J], 1 do
                        SpawnNeutralMinion(NeutralMinionCamps[C], C, J, N)
                        NeutralMinionCamps[C].AliveTracker[N] = true
                        print("good:  CreateRespawnNeutralTimer 2 ")
                    end
                end
            end
    end
end
InitializeNeutralMinionInfo = function()
    local v, w, x, y, z, A, B, T, U, V, W, X, Y, Z, _, a0, a1, a2, a3
    for y = 1, #NeutralMinionCamps, 1 do
        for T = 1, #NeutralMinionCamps[y].Groups, 1 do
            NeutralMinionCamps[y].UniqueNames[T] = {}

         
            for X = 1, #NeutralMinionCamps[y].Groups[T], 1 do
                   --here problem 
                NeutralMinionCamps[y].UniqueNames[T][X] =
                    NeutralMinionCamps[y].Groups[T][X] .. y .. "." .. T .. "." .. X
                    
            end
        end
        z = #NeutralTimers
        NeutralTimers[z + 1] = CreateRespawnNeutralTimer(y)
        NeutralMinionCamps[y].Timer = NeutralTimers[z + 1]
        
        CreateNeutralCamp(NeutralMinionCamps[y], y)
    end
end
SpawnInitialNeutralMinions = function(C)
    local w, x, y, z, A, B, T, U, V, W, X, Y
    if C <= #NeutralMinionCamps then
        x = 0
        y = false
        for T = 1, #NeutralMinionCamps[C].Groups, 1 do
            if 0 < NeutralMinionCamps[C].GroupDelaySpawnTime and y == false then
                NeutralMinionCamps[C].AliveTracker = {}
                for X = 1, #NeutralMinionCamps[C].Groups[T], 1 do
                    NeutralMinionCamps[C].AliveTracker[X] = true
                end
            else
                if math.random(100) <= NeutralMinionCamps[C].GroupsChance[T] + x and y == false then
                    NeutralMinionCamps[C].AliveTracker = {}
                    for X = 1, #NeutralMinionCamps[C].Groups[T], 1 do
                        NeutralMinionCamps[C].AliveTracker[X] = true
                    end
                end
            end
        end
    end
end
NeutralMinionDeath = function(C, a4, a5)
    local y, z, A, B, T, U, V, W, X, Y, Z, _, a0, a1, a2
    z = 0
    for U = 1, #NeutralMinionCamps, 1 do
        for Y = 1, #NeutralMinionCamps[U].UniqueNames, 1 do
            for a1 = 1, #NeutralMinionCamps[U].UniqueNames[Y], 1 do
                if NeutralMinionCamps[U].UniqueNames[Y][a1] == C then
                    z = U
                    NeutralMinionCamps[U].AliveTracker[a1] = false
                end
            end
        end
    end
    if 0 < z then
        for U = 1, #NeutralMinionCamps[z].AliveTracker, 1 do
            if NeutralMinionCamps[z].AliveTracker[U] == true then
                y = false
            end
        end
        if y ~= false then
            InitNeutralMinionTimer(
                NeutralMinionCamps[z].Timer,
                NeutralMinionCamps[z].TimerType,
                NeutralMinionCamps[z].GroupsRespawnTime,
                0,
                false
            )
        end
    end
end
